spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true          # lets Gateway auto-route to any service registered in Eureka
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - AuthenticationFilter

        - id: wishlist-service
          uri: lb://wishlist-service
          predicates:
            - Path=/wishlist/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**